import type { IStatusConfig, IUser, IDocument } from "../types";

export const STATUS_CONFIG: Record<string, IStatusConfig> = {
  Draft: {
    label: "ร่างเอกสาร (Draft)",
    color: "bg-gray-100 text-gray-700 border-gray-200",
  },
  Submitted: {
    label: "ส่งแล้ว (Submitted)",
    color: "bg-blue-50 text-blue-700 border-blue-200",
  },
  Review: {
    label: "กำลังตรวจ (Review)",
    color: "bg-yellow-100 text-yellow-700 border-yellow-200",
  },
  Rejected: {
    label: "ตีกลับ (Rejected)",
    color: "bg-red-100 text-red-700 border-red-200",
  },
  Verified: {
    label: "ตรวจผ่าน (Verified)",
    color: "bg-cyan-100 text-cyan-700 border-cyan-200",
  },
  Approval: {
    label: "รออนุมัติ (Approval)",
    color: "bg-orange-100 text-orange-700 border-orange-200",
  },
  Approved: {
    label: "อนุมัติแล้ว (Approved)",
    color: "bg-emerald-100 text-emerald-700 border-emerald-200",
  },
  Accounting: {
    label: "รอลงบัญชี (Accounting)",
    color: "bg-indigo-100 text-indigo-700 border-indigo-200",
  },
  Posted: {
    label: "ลงบัญชีแล้ว (Posted)",
    color: "bg-violet-100 text-violet-700 border-violet-200",
  },
  Payment: {
    label: "รอจ่ายเงิน (Payment)",
    color: "bg-purple-100 text-purple-700 border-purple-200",
  },
  Paid: {
    label: "จ่ายเงินแล้ว (Paid)",
    color: "bg-green-100 text-green-700 border-green-200",
  },
  Failed: {
    label: "จ่ายล้มเหลว (Failed)",
    color: "bg-rose-100 text-rose-700 border-rose-200",
  },
  Completed: {
    label: "ปิดงาน (Completed)",
    color: "bg-slate-200 text-slate-700 border-slate-300",
  },
};

export const INITIAL_STAGES: string[] = [
  "Draft",
  "Submitted",
  "Review",
  "Verified",
  "Approval",
  "Approved",
  "Accounting",
  "Posted",
  "Payment",
  "Paid",
  "Completed",
];

export const INITIAL_TYPES: string[] = [
  "Invoice",
  "Expense Claim",
  "Purchase Order",
  "Petty Cash",
];

export const INITIAL_USERS: IUser[] = [
  {
    id: "u1",
    name: "John Doe",
    email: "john@company.com",
    role: "User",
    department: "Sales",
  },
  {
    id: "u2",
    name: "Jane Smith",
    email: "jane@company.com",
    role: "Accountant",
    department: "Finance",
  },
  {
    id: "u3",
    name: "Admin Master",
    email: "admin@company.com",
    role: "Admin",
    department: "IT",
  },
  {
    id: "u4",
    name: "Robert Manager",
    email: "robert@company.com",
    role: "Manager",
    department: "Management",
  },
];

export const INITIAL_DOCUMENTS: IDocument[] = [
  {
    document_id: "1",
    document_no: "INV-2024-001",
    document_type: "Invoice",
    description: "ค่าบริการคลาวด์รายเดือน Q4",
    current_status: "Review",
    created_by: "John Doe",
    created_at: "2024-01-01 09:00",
    owner: "Accountant Dept",
  },
  {
    document_id: "2",
    document_no: "EXP-2024-002",
    document_type: "Expense Claim",
    description: "ค่าเดินทางไปพบลูกค้าที่ระยอง",
    current_status: "Completed",
    created_by: "Alice Wong",
    created_at: "2024-01-02 10:30",
    owner: "Archive",
  },
  {
    document_id: "3",
    document_no: "PO-2024-003",
    document_type: "Purchase Order",
    description: "จัดซื้อแล็ปท็อปแผนกการตลาด",
    current_status: "Approval",
    created_by: "Bob Smith",
    created_at: "2024-01-03 14:15",
    owner: "Management",
  },
  {
    document_id: "4",
    document_no: "PC-2024-004",
    document_type: "Petty Cash",
    description: "ค่าอุปกรณ์สำนักงานส่วนกลาง",
    current_status: "Draft",
    created_by: "John Doe",
    created_at: "2024-01-04 11:00",
    owner: "User",
  },
  {
    document_id: "5",
    document_no: "INV-2024-005",
    document_type: "Invoice",
    description: "ค่าบำรุงรักษาอาคารประจำปี",
    current_status: "Payment",
    created_by: "Sarah Connor",
    created_at: "2024-01-05 16:45",
    owner: "Accountant Dept",
  },
  {
    document_id: "6",
    document_no: "EXP-2024-006",
    document_type: "Expense Claim",
    description: "ค่าที่พักดูงานต่างจังหวัด",
    current_status: "Rejected",
    from_status: "Review",
    created_by: "Alice Wong",
    created_at: "2024-01-06 09:20",
    owner: "User",
  },
  {
    document_id: "7",
    document_no: "PO-2024-007",
    document_type: "Purchase Order",
    description: "สั่งซื้อซอฟต์แวร์ลิขสิทธิ์ Adobe",
    current_status: "Accounting",
    created_by: "Charlie Brown",
    created_at: "2024-01-07 13:00",
    owner: "Accountant Dept",
  },
  {
    document_id: "8",
    document_no: "INV-2024-008",
    document_type: "Invoice",
    description: "ค่าโฆษณา Facebook Ads ม.ค.",
    current_status: "Submitted",
    created_by: "Bob Smith",
    created_at: "2024-01-08 10:00",
    owner: "Accountant Dept",
  },
  {
    document_id: "9",
    document_no: "PC-2024-009",
    document_type: "Petty Cash",
    description: "ค่าน้ำดื่มและของว่างรับรองแขก",
    current_status: "Verified",
    created_by: "John Doe",
    created_at: "2024-01-09 15:30",
    owner: "Accountant Dept",
  },
  {
    document_id: "10",
    document_no: "EXP-2024-010",
    document_type: "Expense Claim",
    description: "ค่าไปรษณีย์ส่งเอกสารด่วน",
    current_status: "Posted",
    created_by: "Alice Wong",
    created_at: "2024-01-10 11:10",
    owner: "Accountant Dept",
  },
  {
    document_id: "11",
    document_no: "INV-2024-011",
    document_type: "Invoice",
    description: "ค่าบริการอินเทอร์เน็ตออฟฟิศ",
    current_status: "Approved",
    created_by: "Sarah Connor",
    created_at: "2024-01-11 14:00",
    owner: "Accountant Dept",
  },
  {
    document_id: "12",
    document_no: "PO-2024-012",
    document_type: "Purchase Order",
    description: "โต๊ะทำงานพนักงานใหม่ 5 ชุด",
    current_status: "Paid",
    created_by: "Bob Smith",
    created_at: "2024-01-12 09:45",
    owner: "Accountant Dept",
  },
  {
    document_id: "13",
    document_no: "PC-2024-013",
    document_type: "Petty Cash",
    description: "ค่าจัดเตรียมงานเลี้ยงปีใหม่",
    current_status: "Review",
    created_by: "John Doe",
    created_at: "2024-01-12 16:00",
    owner: "Accountant Dept",
  },
  {
    document_id: "14",
    document_no: "EXP-2024-014",
    document_type: "Expense Claim",
    description: "ค่าทำกุญแจสำรองออฟฟิศ",
    current_status: "Verified",
    created_by: "Alice Wong",
    created_at: "2024-01-13 10:20",
    owner: "Accountant Dept",
  },
  {
    document_id: "15",
    document_no: "INV-2024-015",
    document_type: "Invoice",
    description: "ค่าเช่าเครื่องถ่ายเอกสาร ม.ค.",
    current_status: "Draft",
    created_by: "Bob Smith",
    created_at: "2024-01-13 11:45",
    owner: "User",
  },
  {
    document_id: "16",
    document_no: "INV-2024-016",
    document_type: "Invoice",
    description: "ค่าจ้างทำความสะอาดรายสัปดาห์",
    current_status: "Review",
    created_by: "Sarah Connor",
    created_at: "2024-01-14 08:30",
    owner: "Accountant Dept",
  },
  {
    document_id: "17",
    document_no: "EXP-2024-017",
    document_type: "Expense Claim",
    description: "เบี้ยเลี้ยงเดินทางต่างประเทศ",
    current_status: "Accounting",
    created_by: "Alice Wong",
    created_at: "2024-01-14 10:00",
    owner: "Accountant Dept",
  },
  {
    document_id: "18",
    document_no: "PO-2024-018",
    document_type: "Purchase Order",
    description: "สั่งซื้อเครื่องสำรองไฟ (UPS)",
    current_status: "Approval",
    created_by: "Charlie Brown",
    created_at: "2024-01-14 13:45",
    owner: "Management",
  },
  {
    document_id: "19",
    document_no: "PC-2024-019",
    document_type: "Petty Cash",
    description: "ค่าไปรษณีย์ส่งของขวัญลูกค้า",
    current_status: "Paid",
    created_by: "John Doe",
    created_at: "2024-01-15 09:15",
    owner: "Accountant Dept",
  },
  {
    document_id: "20",
    document_no: "INV-2024-020",
    document_type: "Invoice",
    description: "ค่าลิขสิทธิ์ซอฟต์แวร์ ERP",
    current_status: "Verified",
    created_by: "Bob Smith",
    created_at: "2024-01-15 11:30",
    owner: "Accountant Dept",
  },
  {
    document_id: "21",
    document_no: "PO-2024-021",
    document_type: "Purchase Order",
    description: "เก้าอี้ออฟฟิศใหม่ 2 ตัว",
    current_status: "Draft",
    created_by: "John Doe",
    created_at: "2024-01-16 10:00",
    owner: "User",
  },
];

export const INITIAL_HISTORY = [
  {
    id: "h1",
    document_id: "1",
    from_status: "Draft",
    to_status: "Submitted",
    action: "ส่งตรวจสอบ",
    action_by: "John Doe",
    action_at: "2024-01-01 10:15",
    comment: "เอกสารพร้อมสำหรับการตรวจสอบ",
  },
  {
    id: "h2",
    document_id: "1",
    from_status: "Submitted",
    to_status: "Review",
    action: "รับเรื่องตรวจสอบ",
    action_by: "Jane Smith",
    action_at: "2024-01-01 11:30",
    comment: "เรียบร้อยรับเรื่องแล้ว",
  },
  {
    id: "h3",
    document_id: "2",
    from_status: "Draft",
    to_status: "Submitted",
    action: "ส่งตรวจสอบ",
    action_by: "Alice Wong",
    action_at: "2024-01-02 11:00",
    comment: "ส่งอนุมัติครับ",
  },
  {
    id: "h4",
    document_id: "2",
    from_status: "Submitted",
    to_status: "Review",
    action: "รับเรื่องตรวจสอบ",
    action_by: "Jane Smith",
    action_at: "2024-01-02 12:00",
    comment: "",
  },
  {
    id: "h5",
    document_id: "2",
    from_status: "Review",
    to_status: "Verified",
    action: "ตรวจผ่าน",
    action_by: "Jane Smith",
    action_at: "2024-01-02 13:00",
    comment: "ข้อมูลถูกต้อง",
  },
  {
    id: "h6",
    document_id: "2",
    from_status: "Verified",
    to_status: "Approval",
    action: "ส่งขออนุมัติ",
    action_by: "Jane Smith",
    action_at: "2024-01-02 13:30",
    comment: "",
  },
  {
    id: "h7",
    document_id: "2",
    from_status: "Approval",
    to_status: "Approved",
    action: "อนุมัติเอกสาร",
    action_by: "Robert Manager",
    action_at: "2024-01-02 14:00",
    comment: "อนุมัติเรียบร้อย",
  },
  {
    id: "h8",
    document_id: "2",
    from_status: "Approved",
    to_status: "Accounting",
    action: "รับงานลงบัญชี",
    action_by: "Jane Smith",
    action_at: "2024-01-02 14:30",
    comment: "",
  },
  {
    id: "h9",
    document_id: "2",
    from_status: "Accounting",
    to_status: "Posted",
    action: "ลงรายการบัญชี",
    action_by: "Jane Smith",
    action_at: "2024-01-02 15:00",
    comment: "ลงบัญชีแล้ว",
  },
  {
    id: "h10",
    document_id: "2",
    from_status: "Posted",
    to_status: "Payment",
    action: "เตรียมจ่ายเงิน",
    action_by: "Jane Smith",
    action_at: "2024-01-02 15:30",
    comment: "",
  },
  {
    id: "h11",
    document_id: "2",
    from_status: "Payment",
    to_status: "Paid",
    action: "ยืนยันจ่ายแล้ว",
    action_by: "Jane Smith",
    action_at: "2024-01-02 16:00",
    comment: "จ่ายเงินผ่านบัญชีธนาคารแล้ว",
  },
  {
    id: "h12",
    document_id: "2",
    from_status: "Paid",
    to_status: "Completed",
    action: "ปิดงาน",
    action_by: "Jane Smith",
    action_at: "2024-01-02 16:30",
    comment: "",
  },
  {
    id: "h13",
    document_id: "3",
    from_status: "Draft",
    to_status: "Submitted",
    action: "ส่งตรวจสอบ",
    action_by: "Bob Smith",
    action_at: "2024-01-03 15:00",
    comment: "ยื่นคำขอซื้อครับ",
  },
  {
    id: "h14",
    document_id: "3",
    from_status: "Submitted",
    to_status: "Review",
    action: "รับเรื่องตรวจสอบ",
    action_by: "Jane Smith",
    action_at: "2024-01-03 15:30",
    comment: "",
  },
  {
    id: "h15",
    document_id: "3",
    from_status: "Review",
    to_status: "Verified",
    action: "ตรวจผ่าน",
    action_by: "Jane Smith",
    action_at: "2024-01-03 16:00",
    comment: "ราคาเหมาะสม",
  },
  {
    id: "h16",
    document_id: "3",
    from_status: "Verified",
    to_status: "Approval",
    action: "ส่งขออนุมัติ",
    action_by: "Jane Smith",
    action_at: "2024-01-03 16:15",
    comment: "",
  },
];
